FROM ghcr.io/huggingface/text-generation-inference:latest

WORKDIR /app

RUN pip install text-generation

COPY entrypoints/keep_alive.sh keep_alive.sh
RUN chmod +x keep_alive.sh

ENTRYPOINT ["/app/keep_alive.sh"]

# DOCKER_BUILDKIT=1 docker build -f Dockerfile.pod -t nadahlberg/tgi-runpod:latest --push .
