FROM ghcr.io/huggingface/text-generation-inference:latest

WORKDIR /app

RUN pip install runpod text-generation pathlib

COPY src/handler.py handler.py
COPY entrypoints/start.sh start.sh
RUN chmod +x start.sh

ENTRYPOINT ["/app/start.sh"]

# DOCKER_BUILDKIT=1 docker build -f Dockerfile.serverless -t nadahlberg/tgi-runpod:latest --push .


